//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BookTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookTable()
        {
            this.RentDetailTables = new HashSet<RentDetailTable>();
            this.RentTables = new HashSet<RentTable>();
        }

        [DisplayName("Book ID")]
        public int BookID { get; set; }

        [DisplayName("Book ISBN")]
        public Nullable<int> ISBN { get; set; }

        [DisplayName("Book Status")]
        public Nullable<bool> BookStatus { get; set; }
    
        public virtual BookDetailTable BookDetailTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentDetailTable> RentDetailTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentTable> RentTables { get; set; }
    }
}
