//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class UserInfoTable
    {

        [DisplayName("User ID")]
        public int UserID { get; set; }

        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [DisplayName("Email")]
        public string U_Email { get; set; }

        [DisplayName("Phone Number")]
        public string U_PhoneNumber { get; set; }

        [DisplayName("Address")]
        public string U_Address { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
