//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentTable
    {
        public int RentID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ISBN { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual BookDetailTable BookDetailTable { get; set; }
        public virtual BookTable BookTable { get; set; }
        public virtual RentDetailTable RentDetailTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
